package dev.bitvictory.bitfence.geofence

const val LOCATION_PERMISSION_INDEX = 0
const val BACKGROUND_LOCATION_PERMISSION_INDEX = 1
const val BACKGROUND_ONLY_LOCATION_PERMISSION_INDEX = 0
const val REQUEST_TURN_DEVICE_LOCATION_ON = 29
const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 33
const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
const val REQUEST_BACKGROUND_PERMISSIONS_REQUEST_CODE = 35

const val RADIUS_IN_METER = 100

const val ACTION_GEOFENCE_EVENT =
    "MainActivity.dev.bitvictory.geofencedemo.action.ACTION_GEOFENCE_EVENT"